CC = gcc
CFLAGS = -Wall
THREADS = -pthread

all:
	$(CC) $(CFLAGS) $(THREADS) transfProg.c -o transfProg

debug:
	$(CC) $(CFLAGS) $(THREADS) transfProg.c -g -o transfProg 
	
clean:	
	rm combiner
